services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abogalia-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./prisma/dev.db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      # Add other environment variables here
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
